// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA6MSCl3nsIcmihK5yRpA24Is4Z27CBx4',
    appId: '1:249913587370:web:f2a3b5531f5f78fc2d82d3',
    messagingSenderId: '249913587370',
    projectId: 'iittp-6c38b',
    authDomain: 'iittp-6c38b.firebaseapp.com',
    storageBucket: 'iittp-6c38b.appspot.com',
    measurementId: 'G-XNQVS5J6KB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiqRZ3bfp8VZOg63HIHz0Ga2atsPufsOg',
    appId: '1:249913587370:android:f2fee3456bc8bf9b2d82d3',
    messagingSenderId: '249913587370',
    projectId: 'iittp-6c38b',
    storageBucket: 'iittp-6c38b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE8dTl1_OP_gCU5n42YUBH9l8ea-gS-Hk',
    appId: '1:249913587370:ios:c9185a188b9dcfc32d82d3',
    messagingSenderId: '249913587370',
    projectId: 'iittp-6c38b',
    storageBucket: 'iittp-6c38b.appspot.com',
    iosBundleId: 'com.example.iittpIntegrated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE8dTl1_OP_gCU5n42YUBH9l8ea-gS-Hk',
    appId: '1:249913587370:ios:c9185a188b9dcfc32d82d3',
    messagingSenderId: '249913587370',
    projectId: 'iittp-6c38b',
    storageBucket: 'iittp-6c38b.appspot.com',
    iosBundleId: 'com.example.iittpIntegrated',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA6MSCl3nsIcmihK5yRpA24Is4Z27CBx4',
    appId: '1:249913587370:web:ef70a7b0a5d293332d82d3',
    messagingSenderId: '249913587370',
    projectId: 'iittp-6c38b',
    authDomain: 'iittp-6c38b.firebaseapp.com',
    storageBucket: 'iittp-6c38b.appspot.com',
    measurementId: 'G-JPK5JBHT6M',
  );
}
